import { MapPin, User, Sparkles } from 'lucide-react';

interface Feature {
  icon: typeof MapPin;
  title: string;
  description: string;
  color: string;
}

export default function ValueProposition() {
  const features: Feature[] = [
    {
      icon: MapPin,
      title: 'AI-Powered Itineraries',
      description: 'Get personalized travel plans generated by advanced AI that understands your preferences and style.',
      color: 'bg-luxury-teal',
    },
    {
      icon: Sparkles,
      title: 'Instant Inspiration',
      description: 'Discover amazing destinations and activities tailored to your interests in seconds.',
      color: 'bg-luxury-orange',
    },
    {
      icon: User,
      title: 'Personalized Itineraries',
      description: 'Travel plans uniquely crafted to match your style, interests, and budget for unforgettable adventures.',
      color: 'bg-luxury-teal',
    },
  ];

  return (
    <section className="py-20 px-6 md:px-12 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-light text-luxury-charcoal mb-6" style={{ letterSpacing: '-0.02em' }}>
            Why We Are The Best
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto leading-relaxed">
            We combine cutting-edge technology with personalized service to create unforgettable travel experiences tailored just for you.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <div
                key={index}
                className="group text-center transition-all duration-500 hover:transform hover:scale-105"
              >
                <div className="mb-6 inline-flex">
                  <div
                    className={`${feature.color} rounded-full p-6 transition-all duration-500 group-hover:shadow-glow-teal group-hover:scale-110`}
                  >
                    <Icon className="w-8 h-8 text-white" />
                  </div>
                </div>
                <h3 className="text-xl font-semibold text-luxury-charcoal mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
